on: [push]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Minify
        uses: nizarmah/auto-minify@v3
        with:
          directory: 'cards'
          output: 'out'
          overwrite: true

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: Add auto minified files"
